language: julia
sudo: required
os:
  - linux
#  - osx
julia:
  - 0.4
#  - nightly
notifications:
  email: false

cache:
  directories:
  - $HOME/.julia/v0.4/PETSc2/deps/petsc-3.7.6/arch-linux2-c-debug

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential gfortran perl g++ gcc cmake m4 git
  - sudo apt-get install -y liblapack-dev liblapack-doc liblapack3gf
  - sudo apt-get install -y libblas-dev libblas-doc libblas3gf
  # move the cached files so they don't intefere with the build
  - mv -v $HOME/.julia/v0.4/PETSc2/deps/petsc-3.7.6/arch-linux2-c-debug $HOME/arch-linux2-c-debug
  - rm -vr ~/.julia/v0.4/PETSc2

script:
  -  if [[ -a .git/shallow ]]; then git fetch --unshallow; fi 
  - julia --check-bounds=yes -e 'versioninfo(); Pkg.clone(pwd())'
  - cd ~/.julia/v0.4/PDESolver/deps
  - ./travis-install-mpi.sh mpich3
#  - ./install_cmake3.sh
#  - source ./use_cmake.sh
  - julia --check-bounds=yes -e 'Pkg.build("PDESolver")'
  # move the cached files back
  - mkdir -v $HOME/.julia/v0.4/PETSc2/deps/petsc-3.7.6
  - mv -v $HOME/arch-linux2-c-debug $HOME/.julia/v0.4/PETSc2/deps/petsc-3.7.6/arch-linux2-c-debug
  - cd ~/.julia/v0.4/PumiInterface/src
  - source ./use_julialib.sh
  - cd ~/.julia/v0.4/PDESolver/test
#  - ./runtests_fast.sh
#  - ./runtests_serial.sh
#  - julia ./runtests.jl
#  - cd ./Advection
#  - julia ./runtests_advection.jl
#  - ls ./newton/parallel/
#  - cd ..
#  - ./runtests_parallel.sh
after_success:
#  - julia -e 'cd(Pkg.dir("PDESolver")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#  - julia -e 'cd(Pkg.dir("PDESolver")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("PDESolver"); Pkg.test("PDESolver"; coverage=true)'
